/** Shared layout / component size tokens — 8pt grid. */
export const layout = {
  screenPad: 20,
  /** Board horizontal screen margin */
  boardScreenMargin: 8,
  contentInset: 16,
  sectionGap: 16,
  /** Hard minimum playable tile edge (pt) */
  minTile: 30,
  comfortTile: 40,
  maxTile: 72,
  /** Letter ~50% of tile */
  letterScale: 0.5,
  letterScaleDense: 0.48,
  /** Fixed 2px gap between tiles */
  tileGapPx: 2,
  boardPad: 6,
  boardRadius: 16,
  chromeTop: 56,
  chromeBottom: 80,
  tileRadiusRatio: 0.22,
  tileBevelRatio: 0.08,
  tileBevelMin: 2,
  tileHighlightOpacity: 0.28,
  tileHighlightHeightRatio: 0.4,
  tileSelectedScale: 1.04,
  tileSelectedPulseMs: 900,
  tileShadowOpacity: 0.35,
  tileShadowRadius: 4,
  tileShadowOffsetY: 2,
  tileElevation: 3,
  buttonHeight: 52,
  buttonRadius: 12,
  buttonPadH: 20,
  buttonIconGap: 12,
  buttonLabelSize: 16,
  listButtonHeight: 52,
  listButtonGap: 12,
  iconBtn: 44,
  taglineSize: 12,
  taglineTracking: 1.8,
  logoTile: { sm: 34, md: 52, lg: 72 },
  logoGap: { sm: 6, md: 8, lg: 10 },
  logoGapLg: 10,
  highScoreGap: 16,
  modalRadius: 16,
  modalMaxWidth: 300,
  modalPad: 24,
  controlLabelSize: 11,
  onboardingIllustrationWidthRatio: 0.75,
  onboardingDemoCols: 4,
  onboardingDemoRows: 4,
  onboardingHand: 36,
  onboardingTopPad: 28,
  labelTracking: 1.8,
  titleTracking: -0.3,
  glowCenterOpacity: 0.14,
  /** New Game size-card icon box */
  sizeCardIconH: 72,
  sizeCardH: 140,
} as const;
